apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: ai-platform
spec:
  selector:
    app: open-webui

  ports:
    - name: http
      port: 80
      targetPort: 8080

  type: ClusterIP